learning_log/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

# from learning_logs import views  测试path用法语句


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    # re_path(r'', include('learning_logs.urls',namespace='learning_logs')),与下句等价
    path('', include('learning_logs.urls', namespace='learning_logs')),
    # path('', views.index, name='index')  测试path用法语句，直接映射views也成立
    url(r'mdeditor/', include('mdeditor.urls')),
]
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_logs/urls.py
'''定义learning_logs的URL模式'''
from django.urls import path, re_path
from . import views

# 声明app_name，防止项目中path语句报错
app_name = 'learning_logs'

urlpatterns = [
    # 主页
    # re_path(r'^$', views.index, name='index'),与下句等价
    path('', views.index, name='index'),

    # 显示所有的主题
    # re_path(r'^topics/$', views.topics, name='topics'),与下句等价
    path('topics/', views.topics, name='topics' ),

    # 特定主题的详细页面
    re_path('topics/(?P<topic_id>\d+)/', views.topic, name='topic'),

    # 用于添加新主题的网页
    path('new_topic/', views.new_topic, name='new_topic'),

    # 用于添加新条目的页面
    re_path('new_entry/(?P<topic_id>\d+)/', views.new_entry, name='new_entry'),

    # 用于编辑条目的页面
    re_path('edit_entry/(?P<entry_id>\d+)/', views.edit_entry, name='edit_entry'),

    # 用于显示个人所有的主题
    path('my_topics/', views.my_topics, name='my_topics'),

    # 用于删除自有条目的页面
    re_path('delete_entry/(?P<entry_id>\d+)/', views.delete_entry, name='delete_entry'),

    # 用于删除自有主题的页面
    re_path('delete_topic/(?P<topic_id>\d+)/', views.delete_topic, name='delete_topic'),

]

users/urls.py
'''为应用程序users定义URL模式'''

from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

urlpatterns = [
    # 登录页面
    path('login/', LoginView.as_view(template_name = 'users/login.html'), name='login'),
    # 注销
    path('logout/', views.logout_view, name='logout'),
    # 注册页面
    path('register/', views.register, name='register'),
]
app_name = 'users'

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User
from mdeditor.fields import MDTextField

# Create your models here.
class Topic(models.Model):
    '''用户学习的主题'''
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    public = models.BooleanField(default=False)
    topic_hide = models.BooleanField(default=False)

    def __str__(self):
        '''返回模型的字符串表示'''
        return self.text

class Entry(models.Model):
    '''学到的有关某个主题的具体知识'''
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = MDTextField()
    date_added = models.DateTimeField(auto_now_add=True)
    entry_hide = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        '''返回模型的字符串表示'''
        if len(self.text) > 50:
            return self.text[:50] + '...'
        else:
            return self.text

class ExampleModel(models.Model):
    '''测试模型'''
    name = models.CharField(max_length=10)
    content = MDTextField()

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from .tools import check_topic_owner, check_topic_public


# Create your views here.
def index(request):
    '''学习笔记的主页'''
    return render(request, 'learning_logs/index.html')


def topics(request):
    '''显示所有的主题'''

    topics = Topic.objects.filter(public=True, topic_hide=False).order_by('date_added')
    context = {'topics':topics}
    return render(request, 'learning_logs/topics.html', context)


def topic(request, topic_id):
    '''显示单个主题及其所有的条目'''
    topic = get_object_or_404(Topic, id=topic_id)
    # 确认请求的主题属性为公开
    check_topic_public(topic, request)
    entries = topic.entry_set.filter(entry_hide=False).order_by('-date_added')
    context = {'topic':topic, 'entries':entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    '''添加新主题'''
    if request.method != 'POST':
        # 未提交数据：创建一个新表单
        form = TopicForm()
    else:
        # POST提交的数据，对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            if request.POST.get('dropdown',None) == 'Public':
                new_topic.public = True

            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context={'form':form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    '''在特定的主题中添加新条目'''
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(topic, request)

    if request.method != 'POST':
        # 未提交数据，创建一个新表单
        form = EntryForm()

    else:
        # POST提交的数据，对数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic_id]))
    
    context = {'topic':topic, 'form':form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    '''编辑既有条目'''
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    check_topic_owner(topic, request)

    if request.method != 'POST':
        # 初次请求，使用当前条目填充表单
        form = EntryForm(instance=entry)
    else:
        # POST提交的数据，对数据进行处理
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic.id]))
    
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

@login_required
def my_topics(request):
    '''显示用户个人所有的主题'''

    topics = Topic.objects.filter(owner=request.user, topic_hide=False).order_by('date_added')
    context = {'topics':topics}
    return render(request, 'learning_logs/my_topics.html', context)

@login_required
def delete_entry(request, entry_id):
    '''删除选定条目'''
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    check_topic_owner(topic, request)
    entry.entry_hide = True
    entry.save()

    return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic.id]))

@login_required
def delete_topic(request, topic_id):
    '''删除选定主题'''
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(topic, request)
    topic.topic_hide = True
    topic.save()
    
    return HttpResponseRedirect(reverse('learning_logs:my_topics'))

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def logout_view(request):
    '''注销用户'''
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    '''注册新用户'''
    if request.method != 'POST':
        # 显示空的注册表单
        form = UserCreationForm()
    else:
        # 处理填写好的表单
        form = UserCreationForm(data=request.POST)
    
        if form.is_valid():
            new_user = form.save()
            # 让用户自动登录，再重定向到主页
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    
    context = {'form':form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>学习笔记</title>
    <!-- External CSS -->
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">  
    <!-- External jQuery -->
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <!-- External JavaScript -->
    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- In-document CSS -->
    <style type="text/css">
      a.ex1:hover,a.ex1:active {color:red;}
    </style>
  </head>

  <body>
    <!-- S-Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">

          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            </button>
            <a class="navbar-brand" href="{% url 'learning_logs:index' %}">学习笔记</a>
          </div>

          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="{% url 'learning_logs:topics' %}">公开主题</a></li>
              <li><a href="{% url 'learning_logs:my_topics' %}">我的主题</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}
                <li><a>你好，{{ user.username }}！</a></li>
                <li><a href="{% url 'users:logout' %}">登出</a></li>
              {% else %}
                <li><a href="{% url 'users:register' %}">注册</a></li>
                <li><a href="{% url 'users:login' %}">登入</a></li>
              {% endif %}
            </ul>
          </div>
      </div>
    </nav>
    <!-- E-Static navbar -->

    <!-- S-container -->
      <div class="container">
        <div class="page-header">  
          {% block header %}{% endblock header %}
        </div>
        <div class="">
        {% block content %}{% endblock content %}
        </div>
      </div>
    <!-- E-container -->
  </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>编辑条目</h2>
{% endblock header %}

{% block content %}

  <h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>

  <form role="form" action="{% url 'learning_logs:edit_entry' entry.id %}" method="POST" class="form">
    {% csrf_token %}
    {{ form.media }}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary" style="display:block;margin:0 auto">保存更改</button>
    {% endbuttons %}
  </form>
  
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <div class="jumbotron">
    <h1>记录你的奇思妙想</h1>
  </div>
{% endblock header %}

{% block content %}

  <h2>
    <a href="{% url 'users:register' %}">注册一个账户</a>以开始拥有你自己的学习笔记，然后随时随地记录你学到的点点滴滴。
  </h2><br>
  <h2>
    你可以在<a href="{% url 'learning_logs:my_topics' %}">我的主题</a>中创建新条目，支持 MARK DOWN 格式的书写，期待你的分享！
  </h2><br><br>
  <div class="container">
    <div class="row">
      <h3><p>站点精选</p></h3><br>
      <div class="col-lg-4">
        <a href="{% url 'learning_logs:topic' 7 %}">
          <img src="http://pic.yupoo.com/dxmdmw/b1568393/8e3e5fad.jpg"  width="300" height="240"  alt="图片">
        </a><br>
        <h3><p><strong>笑是最重要的事</strong></p></h3>
      </div>      
      <div class="col-lg-4">
        <a href="{% url 'learning_logs:topic' 11 %}">
          <img src="http://pic.yupoo.com/dxmdmw/558a7765/f61ba11a.jpg"  width="300" height="240"  alt="图片">
        </a><br>
        <h3><p><strong>LeetCode上那些有趣的算法题</strong></p></h3>
        </div>
      <div class="col-lg-4">
          <a href="{% url 'learning_logs:topics' %}">
          <img src="http://pic.yupoo.com/dxmdmw/bf5908c9/3787b25e.jpg"  width="300" height="240"  alt="图片" />
        </a><br>
        <h3><p><strong>查看更多......</strong></p></h3>
      </div>
    </div>
  </div>

{% endblock content %}

learning_logs/templates/learning_logs/my_topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <h1>我的主题</h1>
{% endblock header %}

{% block content %}

  <ul>
    {% for topic in topics %}
      <li>
        <h3>
          <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a> <small>- {{ topic.owner }}</small>
          {% if topic.owner == user %}  
            <small><a href="{% url 'learning_logs:delete_topic' topic.id %}" class="ex1" onclick="return confirm('永久删除此主题，请确认！');"> 删除</a></small>
          {% endif %}
        </h3>
      </li>
    {% empty %}
      <li>您还未创建过任何主题。</li>
    {% endfor %}  
  </ul><br>

  <h3><a href="{% url 'learning_logs:new_topic' %}">创建一个新的主题</h3>

{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>创建一个新的条目：</h2>
{% endblock header %}

{% block content %}

  <h3>
    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
  </h3>

  <form action="{% url 'learning_logs:new_entry' topic.id %}" method="POST" class="form">
    {% csrf_token %}
    {{ form.media }}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary" style="display:block;margin:0 auto">添加新条目</button>
    {% endbuttons %}
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>创建一个新的主题：</h2>
{% endblock header %}

{% block content %}

  <form action="{% url 'learning_logs:new_topic' %}" method="POST" class="form" role="form">

    <select name="dropdown">
      <option value='Public'>公开</option>
      <option value='Private'>私有</option>
    </select>

    {% csrf_token %}
    {% bootstrap_form form %}
    
    {% buttons %}
      <button name="submit" class="btn btn-primary">创建主题</button>
    {% endbuttons %}

  </form>
  
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block header %}
  <h2>{{ topic }}</h2>
  <h4>创建人： {{ topic.owner }}</h4>
{% endblock header %}

{% block content %}

  <p>
    {% if topic.owner == user %}  
      <a href="{% url 'learning_logs:new_entry' topic.id %}">创建一个新条目</a>
    {% endif %}
  </p>
  
  {% for entry in entries %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
          {{ entry.date_added|date:'M d, Y H:i' }}
          {% if topic.owner == user %}  
            <small>
              &nbsp<a href="{% url 'learning_logs:edit_entry' entry.id %}">编辑</a>&nbsp&nbsp
              <a href="{% url 'learning_logs:delete_entry' entry.id %}" class="ex1" onclick="return confirm('永久删除此条目，请确认！');"> 删除</a>
            </small>
          {% endif %}
        </h3>
      </div>
      {% load markdown_deux_tags %}
      <div class="panel-body">
          {{ entry.text|markdown }}
      </div>
    </div>
  {% empty %}
    <li>
      当前主题下还没有创建过任何条目。
    </li>
  {% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <h1>公开主题</h1>
{% endblock header %}

{% block content %}

  <ul>
    {% for topic in topics %}
      <li>
        <h3>
          <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a> <small>- {{ topic.owner }}</small>
          {% if topic.owner == user %}  
            <small><a href="{% url 'learning_logs:delete_topic' topic.id %}" class="ex1" onclick="return confirm('永久删除此主题，请确认！');"> 删除</a></small>
          {% endif %}
        </h3>
      </li>
    {% empty %}
      <li>目前没有已创建的公开主题。</li>
    {% endfor %}  
  </ul><br>

  <h3><a href="{% url 'learning_logs:new_topic' %}">创建一个新的主题</h3>

{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>登录你的账户</h2>
{% endblock header %}

{% block content %}

  <form method="POST" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">登入</button>
    {% endbuttons %}
    
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
  </form>

{% endblock content %}

users/templates/users/register.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2>注册一个新账户</h2>
{% endblock header %}

{% block content %}
  
  <form method="POST" action="{% url 'users:register' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">注册</button>
      <input type="hidden" name="next" value="{% url 'learning_logs:index' %}"/>
    {% endbuttons %}
  </form>
  
{% endblock content %}